In [1]:
######### 케라스의 텍스트 처리 함수 #########
#text 모듈의 text_to_word_sequence()
from tensorflow.keras.preprocessing.text import text_to_word_sequence

text = '데이터 분석을 위한 베이지안 모델링'
result = text_to_word_sequence(text)
print(result)

C:\Users\student\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\student\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\student\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\student\AppData\Roaming\Python\Python

['데이터', '분석을', '위한', '베이지안', '모델링']


In [2]:
#케라스에서 제공하는 BOW를 수행하는 함수 Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer

docs = ['텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토큰화해서 수치 데이터 벡터로 변환해야 딥러닝에서 인식됩니다.',
       '토큰화된 결과는 딥러닝에서 사용할 수 있습니다.']

tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

print(tokenizer.word_counts, '\n') #단어 빈도수 계산 결과 출력됨 (OrderedDict 형태로)
print(tokenizer.document_count, '\n') #문장 개수 출력
print(tokenizer.word_docs, '\n')  #각 단어가 몇개의 문장에 출현하는지 출력
print(tokenizer.word_index, '\n')  #각 단어에 부여된 인덱스 값 출력

OrderedDict([('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해서', 1), ('수치', 1), ('데이터', 1), ('벡터로', 1), ('변환해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화된', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)]) 

3 

defaultdict(<class 'int'>, {'단어를': 1, '각': 1, '토큰화합니다': 1, '텍스트의': 2, '나누어': 1, '딥러닝에서': 2, '변환해야': 1, '데이터': 1, '토큰화해서': 1, '수치': 1, '인식됩니다': 1, '단어로': 1, '벡터로': 1, '결과는': 1, '있습니다': 1, '사용할': 1, '토큰화된': 1, '수': 1}) 

{'텍스트의': 1, '딥러닝에서': 2, '각': 3, '단어를': 4, '나누어': 5, '토큰화합니다': 6, '단어로': 7, '토큰화해서': 8, '수치': 9, '데이터': 10, '벡터로': 11, '변환해야': 12, '인식됩니다': 13, '토큰화된': 14, '결과는': 15, '사용할': 16, '수': 17, '있습니다': 18} 



In [3]:
######### 케라스에서 제공하는 텍스트를 원핫인코딩 변환 함수 : to_categorical #########
text = ['텍스트의 각 단어를 나누어 토큰화합니다.']

token = Tokenizer()
token.fit_on_texts(text)

print(token.word_index)

x = token.texts_to_sequences(text) #토큰의 인덱스로 배열 생성

print(x)

{'텍스트의': 1, '각': 2, '단어를': 3, '나누어': 4, '토큰화합니다': 5}
[[1, 2, 3, 4, 5]]


In [4]:
#케라스 원핫인코딩
from keras.utils import to_categorical

word_size = len(token.word_index) + 1
x = to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 1.]]]


Using TensorFlow backend.


In [5]:
#텍스트의 원핫인코딩 변환은 그대로 사용하기에는 벡터 길이가 너무 길어짐
#공간 낭비를 줄이기 위해 단어 임베딩 방법을 적용
#각 단어 간의 유사도를 계산해서 배열을 새로운 수치값으로 변환
# from keras.layers import Embedding

# model = Sequential()
# #model.add(Embedding(입력 단어 수, 출력될 벡터 크기, input_))

In [6]:
#텍스트 긍정, 부정 예측
import numpy as np
docs = ["너무 재밌어요", "최고예요", "참 잘 만든 영화예요",
        "추천하고 싶은 영화입니다.", "킬링타임용으로 좋아요",
        "글쎄요", "별로예요", "생각보다 지루합니다.",
        "재미없었어요", "그냥 그래요", "3류 영화"]
classes=np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

token = Tokenizer()
token.fit_on_texts(docs) 
print(token.word_index)
x = token.texts_to_sequences(docs)  #토큰의 인덱스로 채운 배열 생성
print("토큰화 결과 " , x)

# 서로 다른 길이의 데이터를 패딩으로 맞춰줍니다.
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_x = pad_sequences(x, 4)
print("\n패딩 결과:\n", padded_x)
#오른쪽 정렬

{'너무': 1, '재밌어요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '킬링타임용으로': 11, '좋아요': 12, '글쎄요': 13, '별로예요': 14, '생각보다': 15, '지루합니다': 16, '재미없었어요': 17, '그냥': 18, '그래요': 19, '3류': 20, '영화': 21}
토큰화 결과  [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12], [13], [14], [15, 16], [17], [18, 19], [20, 21]]

패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0  0 11 12]
 [ 0  0  0 13]
 [ 0  0  0 14]
 [ 0  0 15 16]
 [ 0  0  0 17]
 [ 0  0 18 19]
 [ 0  0 20 21]]


In [7]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Embedding

word_size = len(token.word_index) + 1

model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

print('\nAccuracy: %.4f' % (model.evaluate(padded_x, classes)[1]))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/20
11/11 [==============================] - 0s 35ms/step - loss: 0.6932 - accuracy: 0.2727
Epoch 2/20
11/11 [==============================] - 0s 362us/step - loss: 0.6910 - accuracy: 0.6364
Epoch 3/20
11/11 [==============================] - 0s 363us/step - loss: 0.6887 - accuracy: 0.6364
Epoch 4/20
11/11 [==============================] - 0s 272us/step - loss: 0.6864 - accuracy: 0.7273
Epoch 5/20
11/11 [==============================] - 0s 361us/step - loss: 0.6841 - accuracy: 0.7273
Epoch 6/20
11/11 [==============================] - 0s 361us/step - loss: 0.6818 - accuracy: 0.7273
Epoch 7/20
11/11 [==============================] - 0s 363us/step - loss: 0.6795 - accuracy: 0.7273
Epoch 8/20
11/11 [==============================] - 0s 544us/step - loss: 0.6772 - accuracy: 0.8182
Epoch 9/20
11/11 [==============================] - 0s 364us/step - loss: 0.6749 - accuracy: 0.9091
Epoch 